version: "3.9"

services:
  coordinator:
    image: citusdata/citus:12.1
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=citus
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - coordinator_data:/var/lib/postgresql/data
    networks:
      - citus-network
    restart: always

  worker1:
    image: citusdata/citus:12.1
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=citus
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - worker1_data:/var/lib/postgresql/data
    networks:
      - citus-network
    restart: always

  worker2:
    image: citusdata/citus:12.1
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=citus
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - worker2_data:/var/lib/postgresql/data
    networks:
      - citus-network
    restart: always

networks:
  citus-network:
    driver: bridge

volumes:
  coordinator_data:
  worker1_data:
  worker2_data:
